"""tasks

Revision ID: 0b69cbe62aaa
Revises: f84c985b52c7
Create Date: 2020-07-02 22:40:05.690750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b69cbe62aaa'
down_revision = 'f84c985b52c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task') as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(length=36), nullable=True))
        #batch_op.drop_constraint()
        #batch_op.drop_column('model_id')

    #op.add_column('task', sa.Column('job_id', sa.String(length=36), nullable=True))
    #op.drop_constraint(None, 'task', type_='foreignkey')
    #op.drop_column('task', 'model_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('model_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'task', 'model', ['model_id'], ['id'])
    op.drop_column('task', 'job_id')
    # ### end Alembic commands ###
